================================================================================== FAILURES ===================================================================================
______________________________________________________________________________ test_get_foo[foo] ______________________________________________________________________________

input = 'foo'

    @pytest.mark.parametrize('input', [
        ('foo')
    ])
    def test_get_foo(input):
        output = bar()
>       assert(output == input)
E       AssertionError: assert 'foo-2' == 'foo'
E         
E         - foo
E         + foo-2
E         ?    ++

input      = 'foo'
output     = 'foo-2'

tests/test_foo.py:9: AssertionError
=========================================================================== short test summary info ===========================================================================
FAILED tests/test_foo.py::test_get_foo[foo] - AssertionError: assert 'foo-2' == 'foo'
============================================================================== 1 failed in 0.05s ==============================================================================